export default function Head() {
  return (
    <>
      <title>MelodifyLabs</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://drive.google.com/uc?export=download&id=1OrdAuQD_iWnqLUv1yerPwkvqvgHyw-al"
      />
    </>
  );
}
